sudo: required
services:
  - docker

before_install:
  - docker build -t maroos/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maroos/react-test npm test -- --coverage

after_success:
  - docker build -t maroos/multi-client ./client
  - docker build -t maroos/multi-server ./server
  - docker build -t maroos/multi-worker ./worker
  - docker build -t maroos/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push maroos/multi-client
  - docker push maroos/multi-server
  - docker push maroos/multi-worker
  - docker push maroos/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-eu-west-1-179742641693
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY